services:
  gluetun-nicotine:
    image: qmcgaw/gluetun
    container_name: gluetun-nicotine
    env_file: .env
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=pia
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - OPENVPN_PROTOCOL=tcp
      - REGION=${VPN_REGION}
      - FIREWALL=on
      - HTTP_CONTROL_SERVER=on
      - PORT_FORWARDING=on                                   # Enable PIA port forwarding
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port  # Save port to file
      - VPN_PORT_FORWARDING_UP_COMMAND=sh -c "apk add --no-cache docker-cli && docker exec nicotine /scripts/update-port.sh"
    volumes:
      - ./gluetun:/gluetun  # Stores forwarded_port file
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9080:9080"         # Nicotine+ UI port
    restart: unless-stopped

  nicotineplus-proper:
    image: 'sirjmann92/nicotineplus-proper:latest'
    container_name: nicotine
    restart: unless-stopped
    depends_on:
      - gluetun-nicotine
    network_mode: "service:gluetun-nicotine"
    env_file: .env
    environment:
      - TZ=Europe/Helsinki
      - LANG=C.UTF-8
      - UMASK=022
      - DARKMODE=False
      - LOGIN=${NICO_USER:-username}
      - PASSW=${NICO_PASS:-password}
      - PUID=1000 # Optional: Default is 1000
      - PGID=1000 # Optional: Default is 1000
      - UPNP=False
      - AUTO_CONNECT=True
      - TRAY_ICON=False
      - NOTIFY_FILE=False
      - NOTIFY_FOLDER=False
      - NOTIFY_TITLE=False
      - NOTIFY_PM=False
      - NOTIFY_CHATROOM=False
      - NOTIFY_MENTION=False
      - WEB_UI_PORT=9080 # for custom webUI port assignment. Must match to gluetun one.
    volumes:
      - ${DATA_PATH:-./data}:/data
      - ${CONFIG_PATH:-./config}:/config
      - ${DOWNLOAD_PATH:-./downloads}:/downloads
      - ./gluetun:/gluetun:ro  # Read-only access to forwarded_port
      - ./update-port.sh:/scripts/update-port.sh

